import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";

import { detectDjangoApps } from "../../src/detection/djangoAppDetector";
import { InMemoryFileSystemProbe } from "./fakes/inMemoryFileSystem";

const backendRoot = path.resolve("pc-test-fixtures", "django-apps", "backend");

void test("detects an app generated by startapp (apps.py marker)", async () => {
  const fs = new InMemoryFileSystemProbe().addFile(path.join(backendRoot, "billing", "apps.py"));
  const apps = await detectDjangoApps(fs, backendRoot);
  assert.deepEqual(apps.map((app) => app.name), ["billing"]);
});

void test("detects an older-style app via models.py plus a migrations directory", async () => {
  const fs = new InMemoryFileSystemProbe()
    .addFile(path.join(backendRoot, "legacy", "models.py"))
    .addDirectory(path.join(backendRoot, "legacy", "migrations"));
  const apps = await detectDjangoApps(fs, backendRoot);
  assert.deepEqual(apps.map((app) => app.name), ["legacy"]);
});

void test("does not treat a models.py without a migrations directory as an app", () => {
  const fs = new InMemoryFileSystemProbe().addFile(path.join(backendRoot, "notquite", "models.py"));
  return detectDjangoApps(fs, backendRoot).then((apps) => assert.deepEqual(apps, []));
});

void test("ignores the venv directory and the Django project's own settings package", async () => {
  const fs = new InMemoryFileSystemProbe()
    .addFile(path.join(backendRoot, ".venv", "Scripts", "python.exe"))
    .addFile(path.join(backendRoot, "config", "settings.py"))
    .addFile(path.join(backendRoot, "config", "urls.py"))
    .addFile(path.join(backendRoot, "billing", "apps.py"));

  const apps = await detectDjangoApps(fs, backendRoot);
  assert.deepEqual(apps.map((app) => app.name), ["billing"]);
});

void test("sorts apps alphabetically regardless of directory order", async () => {
  const fs = new InMemoryFileSystemProbe()
    .addFile(path.join(backendRoot, "zeta", "apps.py"))
    .addFile(path.join(backendRoot, "alpha", "apps.py"));

  const apps = await detectDjangoApps(fs, backendRoot);
  assert.deepEqual(apps.map((app) => app.name), ["alpha", "zeta"]);
});

void test("returns nothing for a backend with no app-like directories", async () => {
  const fs = new InMemoryFileSystemProbe().addFile(path.join(backendRoot, "manage.py"));
  const apps = await detectDjangoApps(fs, backendRoot);
  assert.deepEqual(apps, []);
});
